server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/students/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/courses/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teachers/**
        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/common/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
